"""Add auth and multi-tenancy models

Revision ID: 3e5a3d5f3841
Revises: 2259a1d11eb5
Create Date: 2026-08-24 21:02:56.830891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5a3d5f3841'
down_revision: Union[str, None] = '2259a1d11eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('queues', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'queues', 'projects', ['project_id'], ['id'])
    
    # --- Data Migration ---
    import uuid
    from datetime import datetime, timezone
    import bcrypt

    user_id = str(uuid.uuid4())
    org_id = str(uuid.uuid4())
    member_id = str(uuid.uuid4())
    project_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc)
    
    password = "admin"
    password_hash = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

    op.execute(f"INSERT INTO users (id, email, password_hash, name, created_at) VALUES ('{user_id}', 'admin@example.com', '{password_hash}', 'Admin', '{now}')")
    op.execute(f"INSERT INTO organizations (id, name, created_at) VALUES ('{org_id}', 'Default Org', '{now}')")
    op.execute(f"INSERT INTO organization_members (id, organization_id, user_id, role, created_at) VALUES ('{member_id}', '{org_id}', '{user_id}', 'owner', '{now}')")
    op.execute(f"INSERT INTO projects (id, organization_id, name, created_at) VALUES ('{project_id}', '{org_id}', 'Default Project', '{now}')")
    
    op.execute(f"UPDATE queues SET project_id = '{project_id}'")
    
    print("=" * 60)
    print("MIGRATION: Created Default Organization and Project.")
    print("MIGRATION: Created Default User.")
    print("MIGRATION:   Email: admin@example.com")
    print(f"MIGRATION:   Password: {password}")
    print("=" * 60)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queues', type_='foreignkey')
    op.drop_column('queues', 'project_id')
    op.drop_table('api_keys')
    op.drop_table('projects')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
