"""Add idempotency key

Revision ID: 69e8a40b993a
Revises: 164da1b04392
Create Date: 2026-08-25 20:41:38.073368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e8a40b993a'
down_revision: Union[str, None] = '164da1b04392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint('uq_queue_idempotency', 'jobs', ['queue_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_queue_idempotency', 'jobs', type_='unique')
    op.drop_column('jobs', 'idempotency_key')
    # ### end Alembic commands ###
