"""Add ai_summary column to Job

Revision ID: a570e33c6aa1
Revises: 0f064fbac4d0
Create Date: 2026-08-25 21:01:06.999002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a570e33c6aa1'
down_revision: Union[str, None] = '0f064fbac4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ai_summary', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ai_summary')
    # ### end Alembic commands ###
