"""make queue name unique per project

Revision ID: bb4f410e4c86
Revises: 3e5a3d5f3841
Create Date: 2026-08-24 21:27:42.588329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4f410e4c86'
down_revision: Union[str, None] = '3e5a3d5f3841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_queues_name', table_name='queues')
    op.drop_constraint('queues_name_key', 'queues', type_='unique')
    op.create_unique_constraint('uq_project_queue_name', 'queues', ['project_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_queue_name', 'queues', type_='unique')
    op.create_unique_constraint('queues_name_key', 'queues', ['name'])
    op.create_index('ix_queues_name', 'queues', ['name'], unique=True)
    # ### end Alembic commands ###
