"""Add scheduled jobs

Revision ID: fb2bd4ab86cf
Revises: 
Create Date: 2026-08-24 16:13:51.949733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2bd4ab86cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('jobs', sa.Column('cron_expression', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('schedule_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('parent_job_id', sa.UUID(), nullable=True))
    op.create_index('ix_jobs_next_run_at', 'jobs', ['next_run_at'], unique=False)
    op.create_index('ix_jobs_scheduled_at', 'jobs', ['scheduled_at'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_unique_constraint('uq_job_schedule_time', 'jobs', ['schedule_id', 'scheduled_at'])
    op.create_foreign_key(None, 'jobs', 'scheduled_jobs', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint('uq_job_schedule_time', 'jobs', type_='unique')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_scheduled_at', table_name='jobs')
    op.drop_index('ix_jobs_next_run_at', table_name='jobs')
    op.drop_column('jobs', 'parent_job_id')
    op.drop_column('jobs', 'schedule_id')
    op.drop_column('jobs', 'next_run_at')
    op.drop_column('jobs', 'cron_expression')
    op.drop_column('jobs', 'is_recurring')
    op.drop_column('jobs', 'scheduled_at')
    # ### end Alembic commands ###
